name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: vinomaster/mkdocs-ghpages-docker-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
